name: VCMI translations status

on:
  push:
    branches:
      - main
  pull_request:
    paths:
      - "**.py"
  schedule:
    - cron: '0 2 * * 0'
  workflow_dispatch:

jobs:
  update_status:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    steps:
      - uses: actions/checkout@v3
      - name: update status
        run: |
          python3 -m pip install -r requirements.txt
          python3 .github/update.py
      - name: Commit changes
        uses: EndBug/add-and-commit@v9
        with:
          default_author: github_actions
          message: Update status
          add: '*.md'